name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install latest gcc
      run: |
          sudo apt install gcc-14 cmake

    - name: Configure
      run: cmake -S . -B build -DCMAKE_CXX_COMPILER=/usr/bin/g++-14

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
